name: Ansible config new hosts

on:
  push:
    branches: [ "main" ]
    paths:
      - 'ansible/inventory'

env:
  SSH_KEY: ${{ secrets.SSH_KEY }}
  SSH_KEY_INFO: ${{ secrets.SSH_KEY_INFO }}

jobs:
  ansible:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Copy SSH_KEY.
      run: |
        if [ -n "$SSH_KEY" ]; then
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_rsa.pub
          echo "$SSH_KEY_INFO" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa.pub
          chmod 600 ~/.ssh/id_rsa
        else
          echo "SSH_KEY não está definida. Não foi possível escrever no arquivo ~/.ssh/id_rsa.pub"
        fi

    - name: Copy SSH_KEY.
      run: export ANSIBLE_HOST_KEY_CHECKING=False
      
    - name: Run Ansible playbook
      working-directory: ./ansible
      run: |
        ansible-playbook -i inventory config-host.yaml
