name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build the Docker image
      run: docker build ./app --tag carlosbrunodev/app-comments:$(awk -F '=' '{print $2}' ./app/tag-version.txt)

    - name: Push Docker Image to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker push carlosbrunodev/app-comments:$(awk -F '=' '{print $2}' ./app/tag-version.txt)

