name: Terraform Azure Deploy

on:
  push:
    branches: [ "main" ]
    # paths:
    #   - 'terraform/vm/dev.tfvars'

permissions:
  id-token: write
  contents: read
  issues: write

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # - name: 'Az CLI login'
    #   uses: azure/login@v1
    #   with:
    #       client-id: ${{ secrets.AZURE_CLIENT_ID }}
    #       tenant-id: ${{ secrets.AZURE_TENANT_ID }}
    #       subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Check if devtfvars exists
      run: |
        if [ ! -f "terraform/vm/dev.tfvars" ]; then
          echo "File devtfvars not found. Exiting..."
          exit 1
        fi

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    - name: Initialize Terraform
      working-directory: ./terraform/vm
      run: terraform init

    - name: Terraform Plan
      working-directory: ./terraform/vm
      run: terraform plan -var-file=dev.tfvars

    - name: Terraform Apply
      working-directory: ./terraform/vm
      if: github.ref == 'refs/heads/main' && github.event_name == 'push' # Customize this condition based on your branch naming convention
      run: terraform apply -auto-approve -var-file=dev.tfvars
