name: Terraform Azure Deploy

on:
  push:
    branches: [ "main" ]
    # paths:
    #   - 'terraform/vm/dev.tfvars'


env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID}}
  SSH_KEY: ${{ secrets.SSH_KEY}}

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Check if devtfvars exists
      run: |
        # Verifique se a variável SSH_KEY está definida
        if [ -n "$SSH_KEY" ]; then
          # Crie o diretório .ssh se ainda não existir
          mkdir -p ~/.ssh
          
          # Escreva o conteúdo da variável SSH_KEY no arquivo ~/.ssh/id_rsa.pub
          echo "$SSH_KEY" > ~/.ssh/id_rsa.pub
          
          # Defina as permissões corretas no arquivo ~/.ssh/id_rsa.pub
          chmod 600 ~/.ssh/id_rsa.pub
        else
          echo "SSH_KEY não está definida. Não foi possível escrever no arquivo ~/.ssh/id_rsa.pub."
        fi
       
    - name: AZ login
      uses: azure/CLI@v1
      with:
          azcliversion: latest
          inlineScript: |
            az login --service-principal -u $ARM_CLIENT_ID -p $ARM_CLIENT_SECRET --tenant $ARM_TENANT_ID
    
    - name: Check if devtfvars exists
      run: |
        if [ ! -f "terraform/vm/dev.tfvars" ]; then
          echo "File devtfvars not found. Exiting..."
          exit 1
        fi

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    - name: Initialize Terraform
      working-directory: ./terraform/vm
      run: terraform init

    - name: Terraform Plan
      working-directory: ./terraform/vm
      run: terraform plan -var-file=dev.tfvars

    - name: Terraform Apply
      working-directory: ./terraform/vm
      if: github.ref == 'refs/heads/main' && github.event_name == 'push' # Customize this condition based on your branch naming convention
      run: terraform apply -auto-approve -var-file=dev.tfvars
